### ISSUE TITLE
Error message appears when deleting an Item

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/my-recent-items#2]
When deleting an Item (Part, Document,..) an error message appears in FF and Chrome, but not in IE.

Firefox Error Message
![image](https://user-images.githubusercontent.com/32091085/34575787-439e9f0e-f17c-11e7-823f-8bfb416b9dd9.png)

Chrome error message
![image](https://user-images.githubusercontent.com/32091085/34575815-5aa07678-f17c-11e7-97f1-e6281a3c0277.png)

Steps to reproduce:
1.	Open a Part or Document and then close it so it appears in the My Recent Items List
2.	Go to My Recent Items
3.	Open the same Part or Document again
4.	Delete or purge the item
5.	Error message appears

Possible source of problem:
Method: RecentlyVisited_AddToUsersList - Line 19:
` return top.aras.AlertError(thisItem.getErrorString());`

No error message appears when replacing line 19 with
 `return alert(thisItem.getErrorString());`

But I am not sure about this. Needs to be rechecked.

**Comment by EliJDonahue** [comment]
It makes sense that replacing `top.aras.AlertError()` with `alert()` would resolve this error. Using the `top` object is not recommended in Aras 11 SP9+ tabbed client because it can be null, undefined, or defined in a different context. (Hence the Firefox error message "top is null").

When upgrading projects to 11 SP9, try replacing `top.aras` with `aras`.

**Comment by EliJDonahue** [comment]
Fixed in PR #4. Merged into develop branch for now. Will merge develop into master and create a new release when documentation is updated.
